// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj6N0DK9DlNSdkU0kaoA92eVxsP__LZSk',
    appId: '1:23124833070:web:7062c4311933fd5b3000bf',
    messagingSenderId: '23124833070',
    projectId: 'myapp-bdf0e',
    authDomain: 'myapp-bdf0e.firebaseapp.com',
    storageBucket: 'myapp-bdf0e.appspot.com',
    measurementId: 'G-2MLFF08HRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0msRw1Fo3rsDPZkg0vGUVjAHDoIKJRuk',
    appId: '1:23124833070:android:a47c098e9ebbc2f83000bf',
    messagingSenderId: '23124833070',
    projectId: 'myapp-bdf0e',
    storageBucket: 'myapp-bdf0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYPTu5Gvduu4aT4hAWZyHOwtCFVJLl3s0',
    appId: '1:23124833070:ios:7f36e2d6799fc2013000bf',
    messagingSenderId: '23124833070',
    projectId: 'myapp-bdf0e',
    storageBucket: 'myapp-bdf0e.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYPTu5Gvduu4aT4hAWZyHOwtCFVJLl3s0',
    appId: '1:23124833070:ios:7f36e2d6799fc2013000bf',
    messagingSenderId: '23124833070',
    projectId: 'myapp-bdf0e',
    storageBucket: 'myapp-bdf0e.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj6N0DK9DlNSdkU0kaoA92eVxsP__LZSk',
    appId: '1:23124833070:web:e2675e815773e0343000bf',
    messagingSenderId: '23124833070',
    projectId: 'myapp-bdf0e',
    authDomain: 'myapp-bdf0e.firebaseapp.com',
    storageBucket: 'myapp-bdf0e.appspot.com',
    measurementId: 'G-M10G137M6X',
  );
}
